[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ray-mcp"
version = "0.1.0"
description = "MCP (Model Context Protocol) server for Ray distributed computing"
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
dependencies = [
    "ray[default]>=2.30.0",
    "mcp>=1.0.0",
    "pydantic>=2.0.0",
    "click>=8.0.0",
    "asyncio-mqtt>=0.16.0",
    "aiofiles>=23.0.0",
]

[project.optional-dependencies]
examples = ["numpy>=1.21.0"]

[project.urls]
Homepage = "https://github.com/yourusername/ray-mcp"
Documentation = "https://github.com/yourusername/ray-mcp#readme"
Repository = "https://github.com/yourusername/ray-mcp.git"
Issues = "https://github.com/yourusername/ray-mcp/issues"

[project.scripts]
ray-mcp = "ray_mcp.main:run_server"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true 